In [1]:
# Setup()
# Compare_models(): Compare multiples modelos y los ranker 
# Create_model () : Crear un modelo específico
# Tune_models( ):  Ajuste automático del modelo
# Plot_model() : Visualizar el desempeño del modelo
# Evaluate_model() : Evaluación del modelo
# Predict_model() : Predicciones sobre nuevos datos en el Df.
# Save_model/load_model() :

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 

from pycaret.regression import *

In [3]:
df = pd.read_csv(r'C:\Users\Jeffersson Pretell\Documents\Especializacion_ML_Engineering\data\precio_departamentos.csv')

In [4]:
df

,area_m2,num_habitaciones,num_banos,distrito,antiguedad_anos,vista_mar,precio
0,139,1,2,San Isidro,7,0,380619.28
1,96,1,1,San Isidro,7,0,221302.53
2,122,4,1,San Isidro,23,0,338702.68
3,128,2,1,Surco,21,1,341815.62
4,132,3,2,Surco,19,0,346460.60
...,...,...,...,...,...,...,...
95,31,3,2,Miraflores,10,0,108020.65
96,81,2,1,Magdalena,27,0,200124.07
97,74,3,2,San Isidro,14,0,214778.48
98,147,3,2,Magdalena,15,0,417997.49
99,135,1,2,Surco,21,0,354943.60

In [20]:
help(setup)

Help on function setup in module pycaret.regression.functional:

setup(data: Union[dict, list, tuple, numpy.ndarray, scipy.sparse._matrix.spmatrix, pandas.core.frame.DataFrame, NoneType] = None, data_func: Optional[Callable[[], Union[dict, list, tuple, numpy.ndarray, scipy.sparse._matrix.spmatrix, pandas.core.frame.DataFrame]]] = None, target: Union[int, str, list, tuple, numpy.ndarray, pandas.core.series.Series] = -1, index: Union[bool, int, str, list, tuple, numpy.ndarray, pandas.core.series.Series] = True, train_size: float = 0.7, test_data: Union[dict, list, tuple, numpy.ndarray, scipy.sparse._matrix.spmatrix, pandas.core.frame.DataFrame, NoneType] = None, ordinal_features: Optional[Dict[str, list]] = None, numeric_features: Optional[List[str]] = None, categorical_features: Optional[List[str]] = None, date_features: Optional[List[str]] = None, text_features: Optional[List[str]] = None, ignore_features: Optional[List[str]] = None, keep_features: Optional[List[str]] = None, preprocess: bool = True, create_date_columns: List[str] = ['day', 'month', 'year'], imputation_type: Optional[str] = 'simple', numeric_imputation: Union[int, float, str] = 'mean', categorical_imputation: str = 'mode', iterative_imputation_iters: int = 5, numeric_iterative_imputer: Union[str, Any] = 'lightgbm', categorical_iterative_imputer: Union[str, Any] = 'lightgbm', text_features_method: str = 'tf-idf', max_encoding_ohe: int = 25, encoding_method: Optional[Any] = None, rare_to_value: Optional[float] = None, rare_value: str = 'rare', polynomial_features: bool = False, polynomial_degree: int = 2, low_variance_threshold: Optional[float] = None, group_features: Optional[dict] = None, drop_groups: bool = False, remove_multicollinearity: bool = False, multicollinearity_threshold: float = 0.9, bin_numeric_features: Optional[List[str]] = None, remove_outliers: bool = False, outliers_method: str = 'iforest', outliers_threshold: float = 0.05, transformation: bool = False, transformation_method: str = 'yeo-johnson', normalize: bool = False, normalize_method: str = 'zscore', pca: bool = False, pca_method: str = 'linear', pca_components: Union[int, float, str, NoneType] = None, feature_selection: bool = False, feature_selection_method: str = 'classic', feature_selection_estimator: Union[str, Any] = 'lightgbm', n_features_to_select: Union[int, float] = 0.2, transform_target: bool = False, transform_target_method: str = 'yeo-johnson', custom_pipeline: Optional[Any] = None, custom_pipeline_position: int = -1, data_split_shuffle: bool = True, data_split_stratify: Union[bool, List[str]] = False, fold_strategy: Union[str, Any] = 'kfold', fold: int = 10, fold_shuffle: bool = False, fold_groups: Union[str, pandas.core.frame.DataFrame, NoneType] = None, n_jobs: Optional[int] = -1, use_gpu: bool = False, html: bool = True, session_id: Optional[int] = None, system_log: Union[bool, str, logging.Logger] = True, log_experiment: Union[bool, str, pycaret.loggers.base_logger.BaseLogger, List[Union[str, pycaret.loggers.base_logger.BaseLogger]]] = False, experiment_name: Optional[str] = None, experiment_custom_tags: Optional[Dict[str, Any]] = None, log_plots: Union[bool, list] = False, log_profile: bool = False, log_data: bool = False, verbose: bool = True, memory: Union[bool, str, joblib.memory.Memory] = True, profile: bool = False, profile_kwargs: Optional[Dict[str, Any]] = None)
    This function initializes the training environment and creates the transformation
    pipeline. Setup function must be called before executing any other function. It takes
    two mandatory parameters: ``data`` and ``target``. All the other parameters are
    optional.

    Example
    -------
    >>> from pycaret.datasets import get_data
    >>> juice = get_data('juice')
    >>> from pycaret.classification import *
    >>> exp_name = setup(data = juice,  target = 'Purchase')


    data: dataframe-like = None
        Data set with shape (n_samples, n_features), where n_samples is the
        number of samples and n_features is the number of features. If data
        is not a pandas dataframe, it's converted to one using default column
        names.


    data_func: Callable[[], DATAFRAME_LIKE] = None
        The function that generate ``data`` (the dataframe-like input). This
        is useful when the dataset is large, and you need parallel operations
        such as ``compare_models``. It can avoid broadcasting large dataset
        from driver to workers. Notice one and only one of ``data`` and
        ``data_func`` must be set.


    target: int, str or sequence, default = -1
        If int or str, respectivcely index or name of the target column in data.
        The default value selects the last column in the dataset. If sequence,
        it should have shape (n_samples,). The target can be either binary or
        multiclass.


    index: bool, int, str or sequence, default = True
        Handle indices in the `data` dataframe.
            - If False: Reset to RangeIndex.
            - If True: Keep the provided index.
            - If int: Position of the column to use as index.
            - If str: Name of the column to use as index.
            - If sequence: Array with shape=(n_samples,) to use as index.


    train_size: float, default = 0.7
        Proportion of the dataset to be used for training and validation. Should be
        between 0.0 and 1.0.


    test_data: dataframe-like or None, default = None
        If not None, test_data is used as a hold-out set and `train_size` parameter
        is ignored. The columns of data and test_data must match.


    ordinal_features: dict, default = None
        Categorical features to be encoded ordinally. For example, a categorical
        feature with 'low', 'medium', 'high' values where low < medium < high can
        be passed as ordinal_features = {'column_name' : ['low', 'medium', 'high']}.


    numeric_features: list of str, default = None
        If the inferred data types are not correct, the numeric_features param can
        be used to define the data types. It takes a list of strings with column
        names that are numeric.


    categorical_features: list of str, default = None
        If the inferred data types are not correct, the categorical_features param
        can be used to define the data types. It takes a list of strings with column
        names that are categorical.


    date_features: list of str, default = None
        If the inferred data types are not correct, the date_features param can be
        used to overwrite the data types. It takes a list of strings with column
        names that are DateTime.


    text_features: list of str, default = None
        Column names that contain a text corpus. If None, no text features are
        selected.


    ignore_features: list of str, default = None
        ignore_features param can be used to ignore features during preprocessing
        and model training. It takes a list of strings with column names that are
        to be ignored.


    keep_features: list of str, default = None
        keep_features param can be used to always keep specific features during
        preprocessing, i.e. these features are never dropped by any kind of
        feature selection. It takes a list of strings with column names that are
        to be kept.


    preprocess: bool, default = True
        When set to False, no transformations are applied except for train_test_split
        and custom transformations passed in ``custom_pipeline`` param. Data must be
        ready for modeling (no missing values, no dates, categorical data encoding),
        when preprocess is set to False.


    create_date_columns: list of str, default = ["day", "month", "year"]
        Columns to create from the date features. Note that created features
        with zero variance (e.g. the feature hour in a column that only contains
        dates) are ignored. Allowed values are datetime attributes from
        `pandas.Series.dt`. The datetime format of the feature is inferred
        automatically from the first non NaN value.


    imputation_type: str or None, default = 'simple'
        The type of imputation to use. Can be either 'simple' or 'iterative'.
        If None, no imputation of missing values is performed.


    numeric_imputation: int, float or str, default = 'mean'
        Imputing strategy for numerical columns. Ignored when ``imputation_type=
        iterative``. Choose from:
            - "drop": Drop rows containing missing values.
            - "mean": Impute with mean of column.
            - "median": Impute with median of column.
            - "mode": Impute with most frequent value.
            - "knn": Impute using a K-Nearest Neighbors approach.
            - int or float: Impute with provided numerical value.


    categorical_imputation: str, default = 'mode'
        Imputing strategy for categorical columns. Ignored when ``imputation_type=
        iterative``. Choose from:
            - "drop": Drop rows containing missing values.
            - "mode": Impute with most frequent value.
            - str: Impute with provided string.


    iterative_imputation_iters: int, default = 5
        Number of iterations. Ignored when ``imputation_type=simple``.


    numeric_iterative_imputer: str or sklearn estimator, default = 'lightgbm'
        Regressor for iterative imputation of missing values in numeric features.
        If None, it uses LGBClassifier. Ignored when ``imputation_type=simple``.


    categorical_iterative_imputer: str or sklearn estimator, default = 'lightgbm'
        Regressor for iterative imputation of missing values in categorical features.
        If None, it uses LGBClassifier. Ignored when ``imputation_type=simple``.


    text_features_method: str, default = "tf-idf"
        Method with which to embed the text features in the dataset. Choose
        between "bow" (Bag of Words - CountVectorizer) or "tf-idf" (TfidfVectorizer).
        Be aware that the sparse matrix output of the transformer is converted
        internally to its full array. This can cause memory issues for large
        text embeddings.


    max_encoding_ohe: int, default = 25
        Categorical columns with `max_encoding_ohe` or less unique values are
        encoded using OneHotEncoding. If more, the `encoding_method` estimator
        is used. Note that columns with exactly two classes are always encoded
        ordinally. Set to below 0 to always use OneHotEncoding.


    encoding_method: category-encoders estimator, default = None
        A `category-encoders` estimator to encode the categorical columns
        with more than `max_encoding_ohe` unique values. If None,
        `category_encoders.target_encoder.TargetEncoder` is used.


    rare_to_value: float or None, default=None
        Minimum fraction of category occurrences in a categorical column.
        If a category is less frequent than `rare_to_value * len(X)`, it is
        replaced with the string in `rare_value`. Use this parameter to group
        rare categories before encoding the column. If None, ignores this step.


    rare_value: str, default="rare"
        Value with which to replace rare categories. Ignored when
        ``rare_to_value`` is None.


    polynomial_features: bool, default = False
        When set to True, new features are derived using existing numeric features.


    polynomial_degree: int, default = 2
        Degree of polynomial features. For example, if an input sample is two dimensional
        and of the form [a, b], the polynomial features with degree = 2 are:
        [1, a, b, a^2, ab, b^2]. Ignored when ``polynomial_features`` is not True.


    low_variance_threshold: float or None, default = None
        Remove features with a training-set variance lower than the provided
        threshold. If 0, keep all features with non-zero variance, i.e. remove
        the features that have the same value in all samples. If None, skip
        this transformation step.


    group_features: dict or None, default = None
        When the dataset contains features with related characteristics,
        add new fetaures with the following statistical properties of that
        group: min, max, mean, std, median and mode. The parameter takes a
        dict with the group name as key and a list of feature names
        belonging to that group as value.


    drop_groups: bool, default=False
        Whether to drop the original features in the group. Ignored when
        ``group_features`` is None.


    remove_multicollinearity: bool, default = False
        When set to True, features with the inter-correlations higher than
        the defined threshold are removed. For each group, it removes all
        except the feature with the highest correlation to `y`.


    multicollinearity_threshold: float, default = 0.9
        Minimum absolute Pearson correlation to identify correlated
        features. The default value removes equal columns. Ignored when
        ``remove_multicollinearity`` is not True.


    bin_numeric_features: list of str, default = None
        To convert numeric features into categorical, bin_numeric_features parameter can
        be used. It takes a list of strings with column names to be discretized. It does
        so by using 'sturges' rule to determine the number of clusters and then apply
        KMeans algorithm. Original values of the feature are then replaced by the
        cluster label.


    remove_outliers: bool, default = False
        When set to True, outliers from the training data are removed using an
        Isolation Forest.


    outliers_method: str, default = "iforest"
        Method with which to remove outliers. Ignored when `remove_outliers=False`.
        Possible values are:
            - 'iforest': Uses sklearn's IsolationForest.
            - 'ee': Uses sklearn's EllipticEnvelope.
            - 'lof': Uses sklearn's LocalOutlierFactor.


    outliers_threshold: float, default = 0.05
        The percentage of outliers to be removed from the dataset. Ignored
        when ``remove_outliers=False``.


    transformation: bool, default = False
        When set to True, it applies the power transform to make data more Gaussian-like.
        Type of transformation is defined by the ``transformation_method`` parameter.


    transformation_method: str, default = 'yeo-johnson'
        Defines the method for transformation. By default, the transformation method is
        set to 'yeo-johnson'. The other available option for transformation is 'quantile'.
        Ignored when ``transformation`` is not True.


    normalize: bool, default = False
        When set to True, it transforms the features by scaling them to a given
        range. Type of scaling is defined by the ``normalize_method`` parameter.


    normalize_method: str, default = 'zscore'
        Defines the method for scaling. By default, normalize method is set to 'zscore'
        The standard zscore is calculated as z = (x - u) / s. Ignored when ``normalize``
        is not True. The other options are:

        - minmax: scales and translates each feature individually such that it is in
          the range of 0 - 1.
        - maxabs: scales and translates each feature individually such that the
          maximal absolute value of each feature will be 1.0. It does not
          shift/center the data, and thus does not destroy any sparsity.
        - robust: scales and translates each feature according to the Interquartile
          range. When the dataset contains outliers, robust scaler often gives
          better results.


    pca: bool, default = False
        When set to True, dimensionality reduction is applied to project the data into
        a lower dimensional space using the method defined in ``pca_method`` parameter.


    pca_method: str, default = 'linear'
        Method with which to apply PCA. Possible values are:
            - 'linear': Uses Singular Value  Decomposition.
            - 'kernel': Dimensionality reduction through the use of RBF kernel.
            - 'incremental': Similar to 'linear', but more efficient for large datasets.


    pca_components: int, float, str or None, default = None
        Number of components to keep. This parameter is ignored when `pca=False`.
            - If None: All components are kept.
            - If int: Absolute number of components.
            - If float: Such an amount that the variance that needs to be explained
                        is greater than the percentage specified by `n_components`.
                        Value should lie between 0 and 1 (ony for pca_method='linear').
            - If "mle": Minka’s MLE is used to guess the dimension (ony for pca_method='linear').


    feature_selection: bool, default = False
        When set to True, a subset of features is selected based on a feature
        importance score determined by ``feature_selection_estimator``.


    feature_selection_method: str, default = 'classic'
        Algorithm for feature selection. Choose from:
            - 'univariate': Uses sklearn's SelectKBest.
            - 'classic': Uses sklearn's SelectFromModel.
            - 'sequential': Uses sklearn's SequentialFeatureSelector.


    feature_selection_estimator: str or sklearn estimator, default = 'lightgbm'
        Classifier used to determine the feature importances. The
        estimator should have a `feature_importances_` or `coef_`
        attribute after fitting. If None, it uses LGBRegressor. This
        parameter is ignored when `feature_selection_method=univariate`.


    n_features_to_select: int or float, default = 0.2
        The maximum number of features to select with feature_selection. If <1,
        it's the fraction of starting features. Note that this parameter doesn't
        take features in ``ignore_features`` or ``keep_features`` into account
        when counting.


    transform_target: bool, default = False
        When set to True, target variable is transformed using the method defined in
        ``transform_target_method`` param. Target transformation is applied separately
        from feature transformations.


    transform_target_method: str, default = 'yeo-johnson'
        Defines the method for transformation. By default, the transformation method is
        set to 'yeo-johnson'. The other available option for transformation is 'quantile'.
        Ignored when ``transform_target`` is not True.


    custom_pipeline: list of (str, transformer), dict or Pipeline, default = None
        Addidiotnal custom transformers. If passed, they are applied to the
        pipeline last, after all the build-in transformers.


    custom_pipeline_position: int, default = -1
        Position of the custom pipeline in the overal preprocessing pipeline.
        The default value adds the custom pipeline last.


    data_split_shuffle: bool, default = True
        When set to False, prevents shuffling of rows during 'train_test_split'.


    data_split_stratify: bool or list, default = False
        Controls stratification during 'train_test_split'. When set to True, will
        stratify by target column. To stratify on any other columns, pass a list of
        column names. Ignored when ``data_split_shuffle`` is False.


    fold_strategy: str or sklearn CV generator object, default = 'kfold'
        Choice of cross validation strategy. Possible values are:

        * 'kfold'
        * 'groupkfold'
        * 'timeseries'
        * a custom CV generator object compatible with scikit-learn.

        For ``groupkfold``, column name must be passed in ``fold_groups`` parameter.
        Example: ``setup(fold_strategy="groupkfold", fold_groups="COLUMN_NAME")``

    fold: int, default = 10
        Number of folds to be used in cross validation. Must be at least 2. This is
        a global setting that can be over-written at function level by using ``fold``

In [14]:
df.nunique()

area_m2              75
num_habitaciones      4
num_banos             2
distrito              4
antiguedad_anos      28
vista_mar             2
precio              100
dtype: int64

In [5]:
# 1.- Setup()
reg = setup(data = df,target = 'precio',session_id = 123,normalize = True,categorical_features = ['distrito'])

In [6]:
# 2.- Compare_models(): Comparar múltiples modelos y los rankers

best_model = compare_models()

In [7]:
lr = create_model('lr') # Es el mejor modelo

In [8]:
# 4.- Tune_model(): Ajuste automático de hiperparámetros

tuned_lr = tune_model(lr)

Fitting 10 folds for each of 2 candidates, totalling 20 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [9]:
evaluate_model(tuned_lr)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [12]:
preds = predict_model(tuned_lr)

In [11]:
preds.head()

,area_m2,num_habitaciones,num_banos,distrito,antiguedad_anos,vista_mar,precio,prediction_label
8,87,2,2,San Isidro,19,0,242334.515625,229980.233894
70,100,4,2,Miraflores,5,1,300367.437500,323149.386211
82,31,1,1,Surco,14,1,122736.742188,96058.098024
28,97,3,2,Surco,12,1,315150.500000,298969.196595
63,130,1,1,Surco,0,1,364217.593750,361290.005458

In [13]:
# 8.- Save_model/load_model(): Guardar y cargar modelo

save_model(tuned_lr,'modelo_precio_final')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['area_m2', 'num_habitaciones',
                                              'num_banos', 'antiguedad_anos',
                                              'vista_mar'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['distrito'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['distrito'],
                                     transformer=OneHotEncoder(cols=['distrito'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('trained_model', LinearRegression(n_jobs=-1))]),
 'modelo_precio_final.pkl')

| Métrica   | Valor          | Interpretación                                                                                                                         |
| --------- | -------------- | -------------------------------------------------------------------------------------------------------------------------------------- |
| **MAE**   | 12,666.93      | En promedio, las predicciones se equivocan en aproximadamente **12,667 unidades** de la variable objetivo.                             |
| **MSE**   | 222,599,218.68 | Error cuadrático medio. Penaliza fuertemente los errores grandes. Se usa más para optimización que para interpretación directa.        |
| **RMSE**  | 14,919.76      | El error típico de predicción es de aproximadamente **14,920 unidades**. Está en las mismas unidades que la variable dependiente.      |
| **R²**    | 0.9743         | El modelo explica el **97.43% de la variabilidad** de los datos. Es un ajuste excelente.                                               |
| **RMSLE** | 0.0807         | El error relativo en escala logarítmica es bajo. Indica que el modelo mantiene bien las proporciones entre valores grandes y pequeños. |
| **MAPE**  | 0.0576         | Error porcentual medio absoluto de **5.76%**. En promedio, las predicciones se desvían un 5.76% del valor real.                        |